use std::path::PathBuf;

use clap::Parser;
use foundry_backend::{init_logging, run_backend, BackendConfig};

#[derive(Parser, Debug)]
#[command(author, version, about = "Foundry DAG manifest backend.")]
struct Args {
    /// Path to manifest.json generated by `foundry compile`
    #[arg(long, default_value = "manifest.json")]
    manifest: PathBuf,

    /// Address to bind the HTTP server to
    #[arg(long, default_value = "0.0.0.0:8085")]
    addr: String,

    /// Optional directory containing the built frontend assets to serve
    #[arg(long)]
    static_dir: Option<PathBuf>,
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    init_logging();
    let args = Args::parse();
    run_backend(BackendConfig {
        manifest: args.manifest,
        addr: args.addr,
        static_dir: args.static_dir,
    })
    .await
}
