use std::path::PathBuf;
use std::sync::Arc;

use actix_cors::Cors;
use actix_files::Files;
use actix_web::middleware::Logger;
use actix_web::{web, App, HttpResponse, HttpServer, Responder};
use clap::Parser;
use env_logger::Env;
use serde_json::Value;

#[derive(Parser, Debug)]
#[command(author, version, about = "Foundry DAG manifest backend.")]
struct Args {
    /// Path to manifest.json generated by `foundry compile`
    #[arg(long, default_value = "manifest.json")]
    manifest: PathBuf,

    /// Address to bind the HTTP server to
    #[arg(long, default_value = "0.0.0.0:8085")]
    addr: String,

    /// Optional directory containing the built frontend assets to serve
    #[arg(long)]
    static_dir: Option<PathBuf>,
}

#[derive(Clone)]
struct AppState {
    manifest: Arc<Value>,
}

async fn manifest_handler(state: web::Data<AppState>) -> impl Responder {
    let node_count = state
        .manifest
        .get("nodes")
        .and_then(|n| n.as_array())
        .map(|nodes| nodes.len())
        .unwrap_or_default();

    log::info!("serving manifest with {node_count} nodes");
    HttpResponse::Ok().json(&*state.manifest)
}

async fn health_handler() -> impl Responder {
    log::info!("health check requested");
    HttpResponse::Ok().finish()
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    env_logger::Builder::from_env(Env::default().default_filter_or("info")).init();

    let args = Args::parse();
    let manifest_data = std::fs::read_to_string(&args.manifest).unwrap_or_else(|err| {
        eprintln!(
            "failed to read manifest file at '{}': {}",
            args.manifest.display(),
            err
        );
        std::process::exit(1);
    });

    let manifest_json: Value = serde_json::from_str(&manifest_data).unwrap_or_else(|err| {
        eprintln!(
            "failed to parse manifest file at '{}': {}",
            args.manifest.display(),
            err
        );
        std::process::exit(1);
    });

    let state = web::Data::new(AppState {
        manifest: Arc::new(manifest_json),
    });

    let static_dir = args.static_dir.clone();

    log::info!(
        "starting server on {} serving manifest {}",
        args.addr,
        args.manifest.display()
    );

    HttpServer::new(move || {
        let cors = Cors::default()
            .allow_any_origin()
            .allow_any_method()
            .allow_any_header()
            .max_age(3600);

        let mut app = App::new()
            .wrap(Logger::default())
            .wrap(cors)
            .app_data(state.clone())
            .service(web::scope("/api").route("/manifest", web::get().to(manifest_handler)))
            .route("/healthz", web::get().to(health_handler));

        if let Some(dir) = static_dir.clone() {
            app = app.service(
                Files::new("/", dir)
                    .prefer_utf8(true)
                    .index_file("index.html"),
            );
        }

        app
    })
    .bind(args.addr)?
    .run()
    .await
}
