use std::fs;
use actix_web::{web, App, HttpResponse, HttpServer, Responder};
use clap::Parser;

#[derive(Parser, Debug)]
struct Args {
    /// Path to manifest.json generated by `forgery compile`
    #[arg(long, default_value = "manifest.json")]
    manifest: String,
    /// Address to bind the HTTP server to
    #[arg(long, default_value = "0.0.0.0:8085")]
    addr: String,
}

const TEMPLATE: &str = r#"<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>DAG Viewer</title>
<style>
  body { margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Fira Sans', 'Droid Sans', 'Helvetica Neue', Helvetica, Arial, sans-serif; }
  #cy { width: 100%; height: 800px; border: 1px solid #ccc; }
</style>
<script src="https://unpkg.com/cytoscape@3.26.0/dist/cytoscape.min.js"></script>
<script src="https://unpkg.com/dagre@0.8.5/dist/dagre.min.js"></script>
<script src="https://unpkg.com/cytoscape-dagre@2.5.0/cytoscape-dagre.js"></script>
</head>
<body>
<div id="cy"></div>
<script>
const manifest = __MANIFEST__;

const style = [
  {
    selector: 'edge',
    style: {
      'curve-style': 'unbundled-bezier',
      'target-arrow-shape': 'triangle-backcurve',
      'target-arrow-color': '#006f8a',
      'arrow-scale': 1.5,
      'target-distance-from-node': '10px',
      'source-distance-from-node': '5px',
      'line-color': '#006f8a',
      'width': 3,
      'source-endpoint': '50% 0%',
      'target-endpoint': '270deg'
    }
  },
  {
    selector: 'node',
    style: {
      'background-color': '#0094b3',
      'border-color': '#0094b3',
      'font-size': '24px',
      'shape': 'roundrectangle',
      'color': '#fff',
      'width': 'label',
      'height': 'label',
      'padding': '12px',
      'content': 'data(label)',
      'font-weight': 300,
      'font-family': '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Helvetica, Arial, sans-serif',
      'text-valign': 'center',
      'text-halign': 'center',
      'ghost': 'yes',
      'ghost-offset-x': '2px',
      'ghost-offset-y': '4px',
      'ghost-opacity': 0.5,
      'text-outline-color': '#000',
      'text-outline-width': '1px',
      'text-outline-opacity': 0.2
    }
  },
  { selector: 'node[resource_type="source"]', style: { 'background-color': '#5fb825', 'border-color': '#5fb825' }},
  { selector: 'node[resource_type="exposure"]', style: { 'background-color': '#ff694b', 'border-color': '#ff694b' }},
  { selector: 'node[resource_type="metric"]', style: { 'background-color': '#ff5688', 'border-color': '#ff5688' }},
  { selector: 'node[resource_type="semantic_model"]', style: { 'background-color': '#ffa8c2', 'border-color': '#ffa8c2' }},
  { selector: 'node[resource_type="saved_query"]', style: { 'background-color': '#ff7f50', 'border-color': '#ff7f50' }}
];

const nodes = manifest.models.map(m => ({
  data: { id: m.name, label: m.name.split('.').pop(), resource_type: 'model' },
  classes: 'horizontal'
}));

const edges = [];
manifest.models.forEach(m => {
  (m.depends_on || []).forEach(d => {
    const sourceName = manifest.models.find(x => x.name.endsWith('.' + d) || x.name === d);
    const src = sourceName ? sourceName.name : d;
    edges.push({ data: { id: src + '|' + m.name, source: src, target: m.name }, classes: 'horizontal' });
  });
});

cytoscape.use(cytoscapeDagre);
const cy = cytoscape({
  container: document.getElementById('cy'),
  elements: [...nodes, ...edges],
  style: style,
  layout: { name: 'dagre', rankDir: 'LR', rankSep: 200, edgeSep: 30, nodeSep: 50 }
});
</script>
</body>
</html>"#;

async fn dag_page(manifest: web::Data<String>) -> impl Responder {
    let manifest_json = &**manifest;
    let page = TEMPLATE.replace("__MANIFEST__", manifest_json);
    HttpResponse::Ok().content_type("text/html").body(page)
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let args = Args::parse();
    let manifest_data = fs::read_to_string(&args.manifest).expect("read manifest");

    HttpServer::new(move || {
        App::new()
            .app_data(web::Data::new(manifest_data.clone()))
            .route("/dag", web::get().to(dag_page))
    })
    .bind(args.addr)?
    .run()
    .await
}
