from __future__ import annotations

from typing import Final, Literal, overload

from .api import ApiResource, ApiSourceConfig
from .connections import AdapterConnectionDetails
from .db import DbResource
from .kafka import KafkaConnectorResource, KafkaSourceConfig
from . import api, connections, db, kafka


class DataResourceType:
    WAREHOUSE: Final[DataResourceType]
    SOURCE_DB: Final[DataResourceType]
    KAFKA: Final[DataResourceType]
    API: Final[DataResourceType]
    value: str
    def __repr__(self) -> str: ...


class FoundryConfig:
    def __init__(self, project_root: str | None = None) -> None: ...
    def get_db_adapter_details(self, connection_name: str) -> connections.AdapterConnectionDetails: ...
    @property
    def project_name(self) -> str: ...
    @property
    def project_version(self) -> str: ...
    @property
    def compile_path(self) -> str: ...
    @property
    def modelling_architecture(self) -> str: ...
    @property
    def connection_profile(self) -> connections.ConnectionProfile: ...
    def available_connections(self) -> list[str]: ...
    def source_db_names(self) -> list[str]: ...
    def warehouse_source_names(self) -> list[str]: ...
    def kafka_source_names(self) -> list[str]: ...
    def kafka_connector_names(self) -> list[str]: ...
    def get_source_db_config(self, name: str) -> db.DbConfig: ...
    def get_warehouse_db_config(self, name: str) -> db.DbConfig: ...
    def get_kafka_cluster_conn(self, cluster_name: str) -> kafka.KafkaSourceConfig: ...
    def get_kafka_connector_config(self, name: str) -> kafka.KafkaConnectorConfig: ...
    def resolve_db_source(self, name: str, table: str) -> str: ...
    def get_api_source_config(self, name: str) -> api.ApiSourceConfig: ...
    def get_data_endpoint_resource(
        self,
        name: str,
        ep_type: DataResourceType,
        identifier: str | None = None,
    ) -> DbResource | KafkaConnectorResource | ApiResource: ...


@overload
def source(
    *, name: str, ep_type: Literal[DataResourceType.API], identifier: None = None
) -> ApiResource: ...

@overload
def source(
    *, name: str, ep_type: Literal[DataResourceType.SOURCE_DB], identifier: str
) -> DbResource: ...

@overload
def source(
    *, name: str, ep_type: Literal[DataResourceType.KAFKA], identifier: str | None = None
) -> KafkaConnectorResource: ...

@overload
def source(
    *, name: str, ep_type: DataResourceType, identifier: str | None = None
) -> DbResource | KafkaConnectorResource | ApiResource: ...

@overload
def destination(
    *, name: str, ep_type: Literal[DataResourceType.WAREHOUSE], identifier: str
) -> DbResource: ...

@overload
def destination(
    *, name: str, ep_type: DataResourceType, identifier: str | None = None
) -> DbResource | KafkaConnectorResource | ApiResource: ...

def api_source(*, name: str) -> ApiResource: ...
def db_source(*, name: str, identifier: str) -> DbResource: ...
def warehouse_destination(*, name: str, identifier: str) -> DbResource: ...
def kafka_source(*, name: str, identifier: str | None = None) -> KafkaConnectorResource: ...


__all__ = [
    "source",
    "destination",
    "FoundryConfig",
    "DataResourceType",
    "api",
    "connections",
    "db",
    "kafka",
]
