from __future__ import annotations

from .api import ApiSourceConfig
from .connections import AdapterConnectionDetails
from .kafka import KafkaSourceConfig
from . import api, connections, db, kafka


class DataResourceType:
    WAREHOUSE: DataResourceType
    SOURCE_DB: DataResourceType
    KAFKA: DataResourceType
    API: DataResourceType
    value: str
    def __repr__(self) -> str: ...

class DataResourceConfig:
    DB: AdapterConnectionDetails
    KAFKA: KafkaSourceConfig
    API: ApiSourceConfig


class DataResource:
    def __repr__(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def config(self) -> DataResourceConfig: ...


class FoundryConfig:
    def __init__(self, project_root: str | None = None) -> None: ...
    def get_db_adapter_details(self, connection_name: str) -> connections.AdapterConnectionDetails: ...
    @property
    def project_name(self) -> str: ...
    @property
    def project_version(self) -> str: ...
    @property
    def compile_path(self) -> str: ...
    @property
    def modelling_architecture(self) -> str: ...
    @property
    def connection_profile(self) -> connections.ConnectionProfile: ...
    def available_connections(self) -> list[str]: ...
    def source_db_names(self) -> list[str]: ...
    def warehouse_source_names(self) -> list[str]: ...
    def kafka_source_names(self) -> list[str]: ...
    def kafka_connector_names(self) -> list[str]: ...
    def get_source_db_config(self, name: str) -> db.DbConfig: ...
    def get_warehouse_db_config(self, name: str) -> db.DbConfig: ...
    def get_kafka_cluster_conn(self, cluster_name: str) -> kafka.KafkaSourceConfig: ...
    def get_kafka_connector_config(self, name: str) -> kafka.KafkaConnectorConfig: ...
    def resolve_db_source(self, name: str, table: str) -> str: ...
    def get_api_source_config(self, name: str) -> api.ApiSourceConfig: ...
    def get_data_endpoint(self, name: str, ep_type: DataResourceType, identifier: str | None = None) -> DataResource: ...


def source(name: str, ep_type: DataResourceType, identifier: str | None = None) -> DataResource: ...
def destination(name: str, ep_type: DataResourceType, identifier: str | None = None) -> DataResource: ...


__all__ = [
    "source",
    "destination",
    "FoundryConfig",
    "DataResourceType",
    "DataResource",
    "api",
    "connections",
    "db",
    "kafka",
]
