from typing import Optional, Callable, Any, Iterable

class AdapterConnectionDetails:
    host: str
    user: str
    database: str
    password: str
    port: str
    adapter_type: str

class ConnectionProfile:
    profile: str
    path: str

class KafkaBootstrap:
    servers: str

class KafkaConnect:
    host: str
    port: str

class KafkaSourceConfig:
    name: str
    bootstrap: KafkaBootstrap
    connect: KafkaConnect

class KafkaConnectorConfig:
    name: str
    dag_executable: Optional[bool]
    def schema_names(self) -> list[str]: ...
    def table_names(self, schema: str) -> list[str]: ...
    def table_include_list(self) -> str: ...
    def column_include_list(self, fields_only: bool = ...) -> str: ...

class DbConfig:
    name: str
    database: str
    def schema_names(self) -> list[str]: ...
    def table_names(self, schema: str) -> list[str]: ...

class FoundryConfig:
    def __init__(self, project_root: str | None = ...) -> None: ...
    def get_db_adapter_details(self, connection_name: str) -> AdapterConnectionDetails: ...
    @property
    def project_name(self) -> str: ...
    @property
    def project_version(self) -> str: ...
    @property
    def compile_path(self) -> str: ...
    @property
    def modelling_architecture(self) -> str: ...
    @property
    def connection_profile(self) -> ConnectionProfile: ...
    def available_connections(self) -> list[str]: ...
    def source_db_names(self) -> list[str]: ...
    def warehouse_source_names(self) -> list[str]: ...
    def kafka_source_names(self) -> list[str]: ...
    def kafka_connector_names(self) -> list[str]: ...
    def get_source_db_config(self, name: str) -> DbConfig: ...
    def get_warehouse_db_config(self, name: str) -> DbConfig: ...
    def get_kafka_cluster_conn(self, cluster_name: str) -> KafkaSourceConfig: ...
    def get_kafka_connector_config(self, name: str) -> KafkaConnectorConfig: ...
    def resolve_db_source(self, name: str, table: str) -> str: ...

class DbWrapper:
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

def source(name: str) -> str: ...
def destination(name: str) -> str: ...

__all__ = [
    "AdapterConnectionDetails",
    "ConnectionProfile",
    "KafkaBootstrap",
    "KafkaConnect",
    "KafkaSourceConfig",
    "KafkaConnectorConfig",
    "DbConfig",
    "FoundryConfig",
    "DbWrapper",
    "source",
    "destination",
]
