# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import builtins
import typing

@typing.final
class DbConfig:
    @property
    def name(self) -> builtins.str: ...
    @property
    def database(self) -> builtins.str: ...
    def schema_names(self) -> builtins.list[builtins.str]: ...
    def table_names(self, schema: builtins.str) -> builtins.list[builtins.str]: ...

